# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
env:
  global:
    - RGL_USE_NULL=TRUE
addons:
  apt:
    packages:
    - libglu1-mesa-dev
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
after_success:
  - Rscript -e 'covr::codecov()'
